# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Пеленицын Артём Михайлович
title-en:         Artem Pelenitsyn
tagline:          Домашняя страница
tagline-en:       Homepage
baseurl:          http://mmcs.sfedu.ru/~ulysses/
home-ru:          index.rus.html
home-en:          index.html
author:
  name:           Артём Пеленицын
  url:            https://twitter.com/ulysses4ever
  email:          a.pelenitsyn@gmail.com

# Custom vars
version:          0.0.1
mypic:            /~ulysses/Pics/Brazil-2014.jpg

